on:
  push:
    branches:
    - main
  schedule:
    - cron: '1 1 1 * *'

name: Full workflow
jobs:
  createPullRequest:
    runs-on: windows-2019
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} # done in the background.
  # Load repo and install R
    steps:
    - uses: actions/checkout@v4 # takes a clone of the repository onto the VM
    - uses: r-lib/actions/setup-r@v2 # sets up R
    
    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v2 # sets up pandoc (for Markdown)
      with:
        pandoc-version: '2.17.1.1'
    
    - name: Install TinyTeX
      uses: r-lib/actions/setup-tinytex@v2 # sets up tinytex (for LaTeX PDFs)
      env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

    - name: Install dependencies
      run: |
          install.packages(c("rmarkdown", "markdown", "scales"), 
                           dependencies = TRUE, 
                           repos = 'http://cran.rstudio.com/'
                          )
      shell: Rscript {0} 

    - name: Run analysis & generate report
      run: |
          source("analysis.R")
      shell: Rscript {0} 

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7 # creates a pull request
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: auto-report-update
        reviewers: RobertASmith
        commit-message: Automated Model Run & Report Generation
        title: 'Automated Model Run'
        body: >
          Updated report generated.
        labels: report, automated pr